### ISSUE TITLE
No query_id in the final file

### ISSUE THREAD

**Issue by lucianofrancoo** [LeiCao97/PreLnc#2]
Hello, I ran PreLnc successfully with my 105k transcriptome, but the final file does not show the ID of my transcripts, in the delivered data are they in the same input order or were they ordered differently?

**Comment by LeiCao97** [comment]
They are in the same input order. This will be updated later in the process.



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 13, 2021 06:43 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [LeiCao97/PreLnc] No query_id in the final file (#2)




 
Hello, I ran PreLnc successfully with my 105k transcriptome, but the final file does not show the ID of my transcripts, in the delivered data are they in the same input order or were they ordered differently?

**Comment by lucianofrancoo** [comment]
Thx for all, have a nice day
